### ISSUE TITLE
heartbeat timeout and no sync with the player

### ISSUE THREAD

**Issue by linhux** [colloqi/piSignage#119]
Hi, after i have done the install of the latest server here from the github repos have i installed the playerimage for my pi4
But there are some issues:

*    After update if you do not see your groups, please change     *
*    change the uri variable to "mongodb://localhost/pisignage-dev"*
*    in config/env/development.js and restart the server           *
******************************************************************

   info  - socket.io started
Express server listening on port 3000 in development mode
Reset isConnected for 0 players
********************************************
*        system check passed               *
********************************************
Downloading http://pisignage.com/releases/package.json
#Done
disconnect: undefined-undefined;reason: heartbeat timeout
disconnect: undefined-undefined;reason: heartbeat timeout
24 Jun 12:51:01 - unable to find/delete thumbnail: Error: ENOENT: no such file or directory, unlink '/root/media/_thumbnails/Bildschirmfoto 2020-06-22 um 20.03.25.png'
24 Jun 12:51:14 - unable to find/delete thumbnail: Error: ENOENT: no such file or directory, unlink '/root/media/_thumbnails/Bildschirmfoto 2020-06-22 um 20.36.10.png'
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ETIMEDOUT
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'read'
}

**Comment by linhux** [comment]
moved to https://github.com/colloqi/pisignage-server/issues/93
