### ISSUE TITLE
error trying to run start.sh in debian.

### ISSUE THREAD

**Issue by mstrolo** [colloqi/piSignage#175]
2022-04-03T15:41:01: stderr in finding PID of cat /dev/input/by-id:
2022-04-03T15:41:01: Player settings read error: Error: ENOENT: no such file or directory, open '/home/pi/player2/config/_device-settings.json'
2022-04-03T15:41:01: Media settings read error: Error: ENOENT: no such file or directory, open '/home/pi/player2/config/_media-settings.json'
2022-04-03T15:41:02: Could not get MAC addresses: exec error: Error: Command failed: sudo ip -o link
2022-04-03T15:41:02: sudo: no tty present and no askpass program specified
2022-04-03T15:41:02:
2022-04-03T15:41:02: Could not get MAC addresses: exec error: Error: Command failed: sudo ip -o link
2022-04-03T15:41:02: sudo: no tty present and no askpass program specified
2022-04-03T15:41:02:
2022-04-03T15:41:02: TypeError: Cannot read property 'replace' of null
2022-04-03T15:41:02:     at /home/pi/player2/pisignage.js:1:153634
2022-04-03T15:41:02:     at Generator.next (<anonymous>)
2022-04-03T15:41:02:     at ys (/home/pi/player2/pisignage.js:1:152957)
2022-04-03T15:41:02:     at a (/home/pi/player2/pisignage.js:1:153161)
2022-04-03T15:41:02:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-04-03T15:41:04: stderr in finding PID of cat /dev/input/by-id:
2022-04-03T15:41:04: Player settings read error: Error: ENOENT: no such file or directory, open '/home/pi/player2/config/_device-settings.json'
2022-04-03T15:41:04: Media settings read error: Error: ENOENT: no such file or directory, open '/home/pi/player2/config/_media-settings.json'
2022-04-03T15:41:04: Could not get MAC addresses: exec error: Error: Command failed: sudo ip -o link
2022-04-03T15:41:04: sudo: no tty present and no askpass program specified
2022-04-03T15:41:04:

**Comment by AbhijithBn** [comment]
We noticed this error message
>  Could not get MAC addresses: exec error: Error: Command failed: sudo ip -o link
> sudo: no tty present and no askpass program specified

This command failed since you do not have sudo permissions to find out the MAC Address.

To solve this issue,
1) Reference Article Link:  https://pisignage.com/releases/Player2_installation_procedure.html
2) Navigate to  "**Installing on Debian 10/Debian 11/Ubuntu 20**" section
3) Refer Step3
> sudo visudo and add the following as last line
> <username, for e.g. pi> ALL=(ALL) NOPASSWD:ALL


Make sure to follow all the steps under "**Installing on Debian 10/Debian 11/Ubuntu 20**" to run player2 on your Debian system.

Please let us know if you face any other issues.
